### PR TITLE
Allow ucp init() and fin() to be called multiple times

### PR DESCRIPTION
**Pull request by Akshay-Venkatesh**
WIP to address #80

### CODE REVIEW

**Comment by mrocklin** [comment]
Checking in.  What is the status on this?

**Comment by Akshay-Venkatesh** [comment]
@mrocklin The changes here can be pushed to devel but this doesn't address the convenience of using `ucp` module without calling `ucp.init()`. Any thoughts on how can fill that gap?

**Comment by mrocklin** [comment]
Well, this makes it safe for Dask to call `ucp.init()` at import time.  So for our users at least we don't care much.

**Comment by Akshay-Venkatesh** [comment]
Shall I merge this into devel then?

**Comment by mrocklin** [comment]
I'm in favor

**Pull request merged**
